export type CompanyIconName = 
  | 'stripe'
  | 'shopify'
  | 'notion'
  | 'hubspot'
  | 'intercom'
  | 'linear';

export type SocialIconName = 
  | 'twitter'
  | 'github'
  | 'dribbble'
  | 'linkedin'
  | 'facebook'
  | 'instagram'
  | 'threads'
  | 'youtube'
  | 'twitch'
  | 'discord'
  | 'slack'
  | 'reddit'
  | 'pinterest'
  | 'paypal'
  | 'producthunt'
  | 'opencollective';

  export type FeatureIconName = 
  | 'code'
  | 'cloud'
  | 'signal-slash'
  | 'lock'
  | 'users'
  | 'globe'
  | 'bolt'
  | 'shield-check'
  | 'shield-x'
  | 'paperplane'
  | 'chart' 
  | 'chat' 
  | 'shield' 
  | 'clock' 
  | 'brush' 
  | 'layers' 
  | 'zap'
  | 'star'
  | 'heart'
  | 'chevron-right'
  | 'chevron-left'
  | 'chevron-up'
  | 'chevron-down'
  | 'cpu-chip'
  | 'wrench'
  | 'question-mark'
  | 'currency-dollar'
  | 'puzzle-piece'
  | 'squares-plus'
  | 'sparkles';

export type IconName = CompanyIconName | SocialIconName | FeatureIconName;
